### ISSUE TITLE
I need to move a site, but can't add 301-redirect directives

### ISSUE THREAD

**Issue by bitplanets** [dockerfile/ghost#20]
Check the page https://support.google.com/webmasters/answer/83106?hl=en&ref_topic=6029673 it says I need to add the 301-redirect directives but with docker I don't have access to anything to do that.

**Comment by YoussefKababe** [comment]
Hello there! 

This image only contains the default NodeJS server. in order to use directives, you have to run your blog behind Nginx or Apache! To do this you can use the dockerfile/nginx image combined with this image, I'll give you an example using [Fig](http://www.fig.sh/):

```
server:
  image: dockerfile/nginx
  volumes:
    - <sites-enabled-dir>:/etc/nginx/sites-enabled
    - <certs-dir>:/etc/nginx/certs
  ports:
    - "80:80"
    - "443:443"
  links:
    - blog

blog:
  image: dockerfile/ghost
  volumes:
    - <ghost-settings-dir>:/ghost-override
  expose:
    - "2368"
```

Then you have to create a file in your enabled sites directory and write any directives you want there like this:

```
server {
  listen 80;
  server_name example.com;
  return 301 $scheme://www.example.com$request_uri;
}

server {
  listen 80;
  server_name www.example.com;
  client_max_body_size 1M;

  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_pass http://blog_1;
  }
}
```

Notice how I used Nginx as a revese proxy for the Ghost container, and gave it "blog_1" as proxy_pass! "blog_1" is related to the name in fig.yml file, if I named my blog's container "ghost" for example, I would write "ghost_1" instead.
